name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: checks-out this repository under $GITHUB_WORKSPACE(enable to access)
        uses: actions/checkout@v2
#        with:
#          token: ${{ secrets.ACCESS_TOKEN }}
#          submodules: recursive

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Slack Notify
        steps:
          - uses: 8398a7/action-slack@v3
            with:
              status: ${{ job.status }}
              fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
            env:
              SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
            if: always() # Pick up events even if the job fails or is canceled.